### ISSUE TITLE
Fix family in kitty.conf file. you misspelt it to be familly so it wont change font until you remove the extra l. 

### ISSUE THREAD

**Issue by centuryboy774** [elbachir-one/dotfiles#2]

**Comment by elbachir-one** [comment]
Thank you. I managed to fix it.

**Comment by centuryboy774** [comment]
Glad to help! I wonder if you ever noticed the font not working because of the error. I did wanna say thank you for your dotfiles although I only use the kitty.conf part I love your setup it's amazing!
